### ISSUE TITLE
web server isn't running error

### ISSUE THREAD

**Issue by TrickzZ99** [MiniDude22/Pandora-Downloader#12]
I have figured out how to properly launch the flask_server.py file and am using the updated css coding. While the server is active and the download button is pressed, I get an alert saying "(random song)" is downloading" then immediately get "the web server isnt running!". I am unsure what to do from here. I have removed and reapplied the extension itself and stopped and started the flask server, but I run into the same issue. Is there any steps that I am not seeing?

Also, I am confused on how to change the location to which the songs save and how to set the save options. I.e. I would like to save the songs to the automatically add to itunes folder and have the it save as (song name) - (artist).mp3

Any and all help will be appreciated. Thank you in advance!

This is the log I get after a song is attempted to be downloaded. 

![screenshot 5](https://user-images.githubusercontent.com/25786575/38020444-132ed26e-322f-11e8-9502-c4cc76443fee.png)

**Comment by adexcide** [comment]
Getting same error, as well as the buttons not fulling fitting on the page of pandora.com

**Comment by TrickzZ99** [comment]
@adexgold If you go to the issues tab, there is a user that fixed the css coding. I just copied the entire code and replaced it over the original code of the content file within the pandora downloader folder. Copy the updated code, edit the content.css file in the downloader folder using notepad, delete everything in it and paste the new code, and save it. You might have to remove the extension and reapply it for the change to take place. It should properly push both buttons to the right far enough for both of them to perfectly show.

**Comment by MiniDude22** [comment]
Could you get the latest version of the code and see if you're still getting it?

**Comment by TrickzZ99** [comment]
@MiniDude22 Did you update the code onto the main page? If so then I am still running into the same issue. If that wasn't the case I will copy and replace the code within all 4 of the changed files and re run the flask server. Just to be clear all of this should be done in a regular windows command prompt, not the python command prompt.

**Comment by DerrikMilligan** [comment]
The main page? It's pushed to the git so if you redownload it you'll have the new files. And yeah you run the python command in a Windows command prompt if you're in Windows.

**Comment by crypdick** [comment]
@DerrikMilligan @MiniDude22  I just cloned this repo and ran into  this issue. Here's the text of the traceback:

```
127.0.0.1 - - [23/Jul/2018 12:52:29] "POST /download HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/home/shit/bin/anaconda3/lib/python3.6/site-packages/flask/app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/shit/bin/anaconda3/lib/python3.6/site-packages/flask/app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "/home/shit/bin/anaconda3/lib/python3.6/site-packages/flask/app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/shit/bin/anaconda3/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/home/shit/bin/anaconda3/lib/python3.6/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/shit/bin/anaconda3/lib/python3.6/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/shit/bin/anaconda3/lib/python3.6/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/shit/bin/anaconda3/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/home/shit/bin/anaconda3/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/shit/bin/anaconda3/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/shit/bin/Pandora-Downloader/flask_server.py", line 34, in pandoraDownloader
    re.sub(u'[<>\*:\\/\"|?]', '', request.form['station'].encode('utf-8') ) + ".m3u"
  File "/home/shit/bin/anaconda3/lib/python3.6/re.py", line 191, in sub
    return _compile(pattern, flags).sub(repl, string, count)
TypeError: cannot use a string pattern on a bytes-like object
```

**Comment by crypdick** [comment]
I got this plug-in working by gettign rid of a bunch of the encoding/decoding statements that seemed to be make the regexp substitutions break. I'm not sure if this will cause problems for people, but hey, at least the plug-in works for me now. I also updated the calls to `urllib` to be compatible with Python 3. [Here's my fork](https://github.com/crypdick/Pandora-Downloader), happy to submit a PR.

**Comment by DerrikMilligan** [comment]
If that's working then submit a pull request my friend. I have hated all
the encoding issues. Maybe Python3 fixes some of the problems since
everything is unicode to begin with. Seems like a good switch.
